version: "3"

services:
  redis:
    hostname: redis
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  redis-insight:
    hostname: redis-insight
    container_name: redis-insight
    image: "redislabs/redisinsight:latest"
    ports:
      - "5540:5540"
    depends_on:
      - redis

  rust-demo:
    hostname: redis-demo
    container_name: redis-demo
    build:
      context: .
    depends_on:
      - redis
    volumes:
      - ./:/redis_demo
